// fontWeight: {
//   Black: 900,
//   ExtraBold: 800,
//   Bold: 700,
//   SemiBold: 600,
//   Medium: 500,
//   Regular: 500,
//   Light: 300,
//   ExtraLight: 200,
//   Thin: 100,
// },

export const typographyOptions = {
  htmlFontSize: 16,
  fontFamily: 'Pretendard',
  typeface: {
    h1: {
      fontFamily: 'Pretendard',
      fontSize: 48,
      fontWeight: 500,
      lineHeight: '108px',
      letterSpacing: 0,
    },
    h2: {
      fontFamily: 'Pretendard',
      fontSize: 40,
      fontWeight: 600,
      lineHeight: '72px',
      letterSpacing: 0,
    },
    h3: {
      fontFamily: 'Pretendard',
      fontSize: 34,
      fontWeight: 600,
      lineHeight: '60px',
      letterSpacing: 0,
    },
    h4: {
      fontFamily: 'Pretendard',
      fontSize: 30,
      fontWeight: 700,
      lineHeight: '52px',
      letterSpacing: 0,
    },
    h5: {
      fontFamily: 'Pretendard',
      fontSize: 26,
      fontWeight: 600,
      lineHeight: '44px',
      letterSpacing: 0,
    },
    h6: {
      fontFamily: 'Pretendard',
      fontSize: 22,
      fontWeight: 600,
      lineHeight: '36px',
      letterSpacing: 0,
    },
    subtitle1: {
      fontFamily: 'Pretendard',
      fontSize: 22,
      fontWeight: 500,
      lineHeight: '36px',
      letterSpacing: 0,
    },
    subtitle2: {
      fontFamily: 'Pretendard',
      fontSize: 18,
      fontWeight: 600,
      lineHeight: '26px',
      letterSpacing: 0,
    },
    body1: {
      fontFamily: 'Pretendard',
      fontSize: 16,
      fontWeight: 500,
      lineHeight: '28px',
      letterSpacing: 0,
    },
    body2: {
      fontFamily: 'Pretendard',
      fontSize: 14,
      fontWeight: 400,
      lineHeight: '26px',
      letterSpacing: 0,
    },
    caption: {
      fontFamily: 'Pretendard',
      fontSize: 12,
      fontWeight: 400,
      lineHeight: '24px',
      letterSpacing: 0,
    },
    overline: {
      fontFamily: 'Pretendard',
      fontSize: 11,
      fontWeight: 400,
      lineHeight: '23px',
      letterSpacing: 0,
    },
  },
};
